In [3]:
import numpy as np
import pandas as pd
import seaborn as snd
import matplotlib.pyplot as plt

In [22]:
df = pd.read_csv('../all_stocks_5yr.csv')
df.head(100)

          date   open   high    low  close    volume Name
0   2013-02-08  15.07  15.12  14.63  14.75   8407500  AAL
1   2013-02-11  14.89  15.01  14.26  14.46   8882000  AAL
2   2013-02-12  14.45  14.51  14.10  14.27   8126000  AAL
3   2013-02-13  14.30  14.94  14.25  14.66  10259500  AAL
4   2013-02-14  14.94  14.96  13.16  13.99  31879900  AAL
..         ...    ...    ...    ...    ...       ...  ...
95  2013-06-26  16.50  16.64  16.17  16.17   3604500  AAL
96  2013-06-27  16.29  16.34  16.00  16.31   3566000  AAL
97  2013-06-28  16.24  16.55  16.16  16.42   7063900  AAL
98  2013-07-01  16.50  17.04  16.48  16.80   4666900  AAL
99  2013-07-02  16.78  16.79  16.36  16.43   4009300  AAL

[100 rows x 7 columns]

Data Exploration

In [7]:
df.describe()

,open,high,low,close,volume
count,619029.000000,619032.000000,619032.000000,619040.000000,6.190400e+05
mean,83.023334,83.778311,82.256096,83.043763,4.321823e+06
std,97.378769,98.207519,96.507421,97.389748,8.693610e+06
min,1.620000,1.690000,1.500000,1.590000,0.000000e+00
25%,40.220000,40.620000,39.830000,40.245000,1.070320e+06
50%,62.590000,63.150000,62.020000,62.620000,2.082094e+06
75%,94.370000,95.180000,93.540000,94.410000,4.284509e+06
max,2044.000000,2067.990000,2035.110000,2049.000000,6.182376e+08

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 619040 entries, 0 to 619039
Data columns (total 7 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   date    619040 non-null  object
 1   open    619029 non-null  float64
 2   high    619032 non-null  float64
 3   low     619032 non-null  float64
 4   close   619040 non-null  float64
 5   volume  619040 non-null  int64
 6   Name    619040 non-null  object
dtypes: float64(4), int64(1), object(2)
memory usage: 33.1+ MB

In [8]:
df.isnull().sum()

date       0
open      11
high       8
low        8
close      0
volume     0
Name       0
dtype: int64

In [11]:
df['Name'].unique()

array(['AAL', 'AAPL', 'AAP', 'ABBV', 'ABC', 'ABT', 'ACN', 'ADBE', 'ADI',
       'ADM', 'ADP', 'ADSK', 'ADS', 'AEE', 'AEP', 'AES', 'AET', 'AFL',
       'AGN', 'AIG', 'AIV', 'AIZ', 'AJG', 'AKAM', 'ALB', 'ALGN', 'ALK',
       'ALLE', 'ALL', 'ALXN', 'AMAT', 'AMD', 'AME', 'AMGN', 'AMG', 'AMP',
       'AMT', 'AMZN', 'ANDV', 'ANSS', 'ANTM', 'AON', 'AOS', 'APA', 'APC',
       'APD', 'APH', 'APTV', 'ARE', 'ARNC', 'ATVI', 'AVB', 'AVGO', 'AVY',
       'AWK', 'AXP', 'AYI', 'AZO', 'A', 'BAC', 'BAX', 'BA', 'BBT', 'BBY',
       'BDX', 'BEN', 'BF.B', 'BHF', 'BHGE', 'BIIB', 'BK', 'BLK', 'BLL',
       'BMY', 'BRK.B', 'BSX', 'BWA', 'BXP', 'CAG', 'CAH', 'CAT', 'CA',
       'CBG', 'CBOE', 'CBS', 'CB', 'CCI', 'CCL', 'CDNS', 'CELG', 'CERN',
       'CFG', 'CF', 'CHD', 'CHK', 'CHRW', 'CHTR', 'CINF', 'CI', 'CLX',
       'CL', 'CMA', 'CMCSA', 'CME', 'CMG', 'CMI', 'CMS', 'CNC', 'CNP',
       'COF', 'COG', 'COL', 'COO', 'COP', 'COST', 'COTY', 'CPB', 'CRM',
       'CSCO', 'CSRA', 'CSX', 'CTAS', 'CTL', 'CTSH', 'CTXS', 'CVS', 'CVX',
       'CXO', 'C', 'DAL', 'DE', 'DFS', 'DGX', 'DG', 'DHI', 'DHR', 'DISCA',
       'DISCK', 'DISH', 'DIS', 'DLR', 'DLTR', 'DOV', 'DPS', 'DRE', 'DRI',
       'DTE', 'DUK', 'DVA', 'DVN', 'DWDP', 'DXC', 'D', 'EA', 'EBAY',
       'ECL', 'ED', 'EFX', 'EIX', 'EL', 'EMN', 'EMR', 'EOG', 'EQIX',
       'EQR', 'EQT', 'ESRX', 'ESS', 'ES', 'ETFC', 'ETN', 'ETR', 'EVHC',
       'EW', 'EXC', 'EXPD', 'EXPE', 'EXR', 'FAST', 'FBHS', 'FB', 'FCX',
       'FDX', 'FE', 'FFIV', 'FISV', 'FIS', 'FITB', 'FLIR', 'FLR', 'FLS',
       'FL', 'FMC', 'FOXA', 'FOX', 'FRT', 'FTI', 'FTV', 'F', 'GD', 'GE',
       'GGP', 'GILD', 'GIS', 'GLW', 'GM', 'GOOGL', 'GOOG', 'GPC', 'GPN',
       'GPS', 'GRMN', 'GS', 'GT', 'GWW', 'HAL', 'HAS', 'HBAN', 'HBI',
       'HCA', 'HCN', 'HCP', 'HD', 'HES', 'HIG', 'HII', 'HLT', 'HOG',
       'HOLX', 'HON', 'HPE', 'HPQ', 'HP', 'HRB', 'HRL', 'HRS', 'HSIC',
       'HST', 'HSY', 'HUM', 'IBM', 'ICE', 'IDXX', 'IFF', 'ILMN', 'INCY',
       'INFO', 'INTC', 'INTU', 'IPG', 'IP', 'IQV', 'IRM', 'IR', 'ISRG',
       'ITW', 'IT', 'IVZ', 'JBHT', 'JCI', 'JEC', 'JNJ', 'JNPR', 'JPM',
       'JWN', 'KEY', 'KHC', 'KIM', 'KLAC', 'KMB', 'KMI', 'KMX', 'KORS',
       'KO', 'KR', 'KSS', 'KSU', 'K', 'LB', 'LEG', 'LEN', 'LH', 'LKQ',
       'LLL', 'LLY', 'LMT', 'LNC', 'LNT', 'LOW', 'LRCX', 'LUK', 'LUV',
       'LYB', 'L', 'MAA', 'MAC', 'MAR', 'MAS', 'MAT', 'MA', 'MCD', 'MCHP',
       'MCK', 'MCO', 'MDLZ', 'MDT', 'MET', 'MGM', 'MHK', 'MKC', 'MLM',
       'MMC', 'MMM', 'MNST', 'MON', 'MOS', 'MO', 'MPC', 'MRK', 'MRO',
       'MSFT', 'MSI', 'MS', 'MTB', 'MTD', 'MU', 'MYL', 'M', 'NAVI', 'NBL',
       'NCLH', 'NDAQ', 'NEE', 'NEM', 'NFLX', 'NFX', 'NI', 'NKE', 'NLSN',
       'NOC', 'NOV', 'NRG', 'NSC', 'NTAP', 'NTRS', 'NUE', 'NVDA', 'NWL',
       'NWSA', 'NWS', 'OKE', 'OMC', 'ORCL', 'ORLY', 'OXY', 'O', 'PAYX',
       'PBCT', 'PCAR', 'PCG', 'PCLN', 'PDCO', 'PEG', 'PEP', 'PFE', 'PFG',
       'PGR', 'PG', 'PHM', 'PH', 'PKG', 'PKI', 'PLD', 'PM', 'PNC', 'PNR',
       'PNW', 'PPG', 'PPL', 'PRGO', 'PRU', 'PSA', 'PSX', 'PVH', 'PWR',
       'PXD', 'PX', 'PYPL', 'QCOM', 'QRVO', 'RCL', 'REGN', 'REG', 'RE',
       'RF', 'RHI', 'RHT', 'RJF', 'RL', 'RMD', 'ROK', 'ROP', 'ROST',
       'RRC', 'RSG', 'RTN', 'SBAC', 'SBUX', 'SCG', 'SCHW', 'SEE', 'SHW',
       'SIG', 'SJM', 'SLB', 'SLG', 'SNA', 'SNI', 'SNPS', 'SO', 'SPGI',
       'SPG', 'SRCL', 'SRE', 'STI', 'STT', 'STX', 'STZ', 'SWKS', 'SWK',
       'SYF', 'SYK', 'SYMC', 'SYY', 'TAP', 'TDG', 'TEL', 'TGT', 'TIF',
       'TJX', 'TMK', 'TMO', 'TPR', 'TRIP', 'TROW', 'TRV', 'TSCO', 'TSN',
       'TSS', 'TWX', 'TXN', 'TXT', 'T', 'UAA', 'UAL', 'UA', 'UDR', 'UHS',
       'ULTA', 'UNH', 'UNM', 'UNP', 'UPS', 'URI', 'USB', 'UTX', 'VAR',
       'VFC', 'VIAB', 'VLO', 'VMC', 'VNO', 'VRSK', 'VRSN', 'VRTX', 'VTR',
       'VZ', 'V', 'WAT', 'WBA', 'WDC', 'WEC', 'WFC', 'WHR', 'WLTW', 'WMB',
       'WMT', 'WM', 'WRK', 'WU', 'WYNN', 'WYN', 'WY', 'XEC', 'XEL',
       'XLNX', 'XL', 'XOM', 'XRAY', 'XRX', 'XYL', 'YUM', 'ZBH', 'ZION',
       'ZTS'], dtype=object)

Data Cleaning and Pre-Processing

In [23]:
# Dropping the Null columns
df.dropna(inplace=True)

# Changing the Date format from object to Datetime
df['date'] = pd.to_datetime(df['date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 619029 entries, 0 to 619039
Data columns (total 7 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   date    619029 non-null  datetime64[ns]
 1   open    619029 non-null  float64
 2   high    619029 non-null  float64
 3   low     619029 non-null  float64
 4   close   619029 non-null  float64
 5   volume  619029 non-null  int64
 6   Name    619029 non-null  object
dtypes: datetime64[ns](1), float64(4), int64(1), object(1)
memory usage: 37.8+ MB

In [35]:
# Calculating the average trade of all stocks in the dataset and sorting it in order to get the Top 10 which will be used for further analysis
data_dict = {}
print("Unique count for ticker column : " , df['Name'].nunique())
print()
for ticker in df['Name'].unique():
    avg = df[df['Name'] == ticker]['volume'].mean()
    data_dict[ticker] = avg
print("All stocks with respective avegrae trade volumes : " ,  data_dict)

sorted_items = sorted(data_dict.items(), key=lambda item: item[1], reverse=True)[:10]
top_10 = {item[0]: item[1] for item in sorted_items}
print()
print("Top 10 stocks with highest trade volume : " , top_10.keys())

Unique count for ticker column :  505

All stocks with respective avegrae trade volumes :  {'AAL': 9390321.324066719, 'AAPL': 54047899.73550437, 'AAP': 1078043.216838761, 'ABBV': 7870682.665607625, 'ABC': 2005738.3232724385, 'ABT': 6964036.691818904, 'ACN': 2596238.098490866, 'ADBE': 2998133.5996822873, 'ADI': 2451738.088959492, 'ADM': 3647857.6870532166, 'ADP': 2022774.221604448, 'ADSK': 2482750.679110405, 'ADS': 619308.5424940429, 'AEE': 1622724.4956314536, 'AEP': 2781243.0254169977, 'AES': 5568655.816521049, 'AET': 2716448.100873709, 'AFL': 2116351.5226370133, 'AGN': 2880076.8125496428, 'AIG': 8419467.383637808, 'AIV': 1198721.3010325655, 'AIZ': 545139.3129467831, 'AJG': 924431.0667196187, 'AKAM': 2182469.447180302, 'ALB': 1160881.819698173, 'ALGN': 885551.828435266, 'ALK': 1537615.6846703733, 'ALLE': 739724.4948259642, 'ALL': 2407102.868149325, 'ALXN': 1762434.8204924543, 'AMAT': 13230027.8649722, 'AMD': 32519037.79666402, 'AME': 1308148.1326449562, 'AMGN': 3465404.566322478, 'AMG': 451857.10166799044, 'AMP': 1132200.868943606, 'AMT': 2280151.30420969, 'AMZN': 3730465.46624305, 'ANDV': 2617506.42573471, 'ANSS': 439197.7855440826, 'ANTM': 1883323.538522637, 'AON': 1328024.8760921366, 'AOS': 1259603.602065131, 'APA': 3832411.795869738, 'APC': 4972386.501985703, 'APD': 1329444.9221604448, 'APH': 1224710.4996028594, 'APTV': 2112449.522727273, 'ARE': 527525.8800635425, 'ARNC': 6826431.219221604, 'ATVI': 7658033.0325655285, 'AVB': 771412.7760127085, 'AVGO': 2846907.2748212866, 'AVY': 760835.4694201747, 'AWK': 943796.4718030182, 'AXP': 4773412.951548848, 'AYI': 483442.64892772044, 'AZO': 315794.3820492454, 'A': 2338038.906274821, 'BAC': 93633799.51628277, 'BAX': 4093500.5281969816, 'BA': 4178966.0389197776, 'BBT': 4188795.4130262113, 'BBY': 5711082.543288324, 'BDX': 1080620.620333598, 'BEN': 2559382.2144559175, 'BF.B': 976498.9197776013, 'BHF': 1020270.3450704225, 'BHGE': 4133638.4342105263, 'BIIB': 1645028.2295472596, 'BK': 5347609.725972994, 'BLK': 639737.6338363781, 'BLL': 2361623.2009531376, 'BMY': 8025117.671439936, 'BRK.B': 3583172.6918189037, 'BSX': 10841879.173153296, 'BWA': 1884110.4106433678, 'BXP': 812103.6155679111, 'CAG': 3323246.552819698, 'CAH': 2406523.5091342335, 'CAT': 5404720.888800635, 'CA': 2777285.909451946, 'CBG': 2274285.05401112, 'CBOE': 729603.2557585385, 'CBS': 5512626.426528991, 'CB': 1564006.8697378873, 'CCI': 2431933.0611596503, 'CCL': 4110469.745035743, 'CDNS': 2905825.397934869, 'CELG': 5335037.008737093, 'CERN': 2035070.637013503, 'CFG': 5253957.750588235, 'CF': 4247865.39158062, 'CHD': 1554292.1374106433, 'CHK': 24957711.172359016, 'CHRW': 1589710.656076251, 'CHTR': 1559207.6314535346, 'CINF': 598607.2176330421, 'CI': 1634202.1890389198, 'CLX': 975512.8061953932, 'CL': 3301235.9205718823, 'CMA': 1929065.597299444, 'CMCSA': 24329297.557585385, 'CME': 1612700.4503574264, 'CMG': 820579.4757744242, 'CMI': 1630509.4868943605, 'CMS': 2350950.122319301, 'CNC': 1575350.321683876, 'CNP': 3725276.3542494043, 'COF': 3112814.806195393, 'COG': 6039257.025416997, 'COL': 1026225.6036536935, 'COO': 452728.4646544877, 'COP': 7499280.843526608, 'COST': 2317919.6767275617, 'COTY': 2995484.568627451, 'CPB': 1783601.5806195394, 'CRM': 5079399.206513106, 'CSCO': 28654349.631453533, 'CSRA': 1258491.1515151516, 'CSX': 7756074.243844321, 'CTAS': 602204.9237490072, 'CTL': 6695583.1405877685, 'CTSH': 4403324.354249405, 'CTXS': 1956169.8999205718, 'CVS': 5605183.055599682, 'CVX': 7070167.099285147, 'CXO': 1443521.923749007, 'C': 20686758.37807784, 'DAL': 11005102.131850675, 'DE': 3002921.157267673, 'DFS': 3080513.0675139, 'DGX': 1368237.43923749, 'DG': 3579369.4154090546, 'DHI': 5357329.629070691, 'DHR': 2897171.02739726, 'DISCA': 3067299.4900714853, 'DISCK': 1717430.4948371723, 'DISH': 2337027.1334392377, 'DIS': 7647465.507545671, 'DLR': 1424176.6640190626, 'DLTR': 2551309.1485305796, 'DOV': 1350967.9301032566, 'DPS': 1406456.6997617157, 'DRE': 2528068.8300238284, 'DRI': 1676379.841938046, 'DTE': 1043527.0333598094, 'DUK': 3123141.41223193, 'DVA': 1440931.9698173152, 'DVN': 5117704.09451946, 'DWDP': 7987472.449541285, 'DXC': 1974555.3255813953, 'D': 2619407.4082605243, 'EA': 3786907.980937252, 'EBAY': 10910270.131056394, 'ECL': 1097335.0389197776, 'ED': 1974371.5393169182, 'EFX': 818882.823669579, 'EIX': 2134890.1818903894, 'EL': 1799581.4654487688, 'EMN': 1386564.1938046068, 'EMR': 3746098.411437649, 'EOG': 3889026.162827641, 'EQIX': 744558.3105639396, 'EQR': 1917699.6354249404, 'EQT': 1931493.683081811, 'ESRX': 4416324.65528197, 'ESS': 378875.95869737887, 'ES': 1602363.967948718, 'ETFC': 3428001.8649722002, 'ETN': 2834895.6266878475, 'ETR': 1427922.5512311358, 'EVHC': 2251115.0134680136, 'EW': 2073080.54725973, 'EXC': 6562701.988085782, 'EXPD': 1390130.4694201748, 'EXPE': 2300193.7180301826, 'EXR': 934249.3002382844, 'FAST': 2431755.28355838, 'FBHS': 1327430.416203336, 'FB': 34359265.20969023, 'FCX': 23549216.57426529, 'FDX': 1837186.1969817316, 'FE': 3907825.496425735, 'FFIV': 1141482.6894360604, 'FISV': 1075009.366163622, 'FIS': 1579718.7895154885, 'FITB': 7466531.101667991, 'FLIR': 947756.5289912629, 'FLR': 1507770.5639396347, 'FLS': 1280979.6981731532, 'FL': 2459645.0460683084, 'FMC': 1156382.624305004, 'FOXA': 11797312.638152268, 'FOX': 3556472.5577416597, 'FRT': 421801.35266084195, 'FTI': 2994211.212867355, 'FTV': 1515111.8436724567, 'F': 34462374.8943606, 'GD': 1576676.1366163623, 'GE': 42115682.83240667, 'GGP': 4718237.749007149, 'GILD': 11165045.750595711, 'GIS': 3335350.1771247024, 'GLW': 9407878.969023034, 'GM': 15058577.684670374, 'GOOGL': 2457501.4948371723, 'GOOG': 1808413.801025641, 'GPC': 752244.5281969818, 'GPN': 1396879.3717235902, 'GPS': 5157228.138999206, 'GRMN': 1322828.9316918189, 'GS': 3249413.787132645, 'GT': 3599274.9444003175, 'GWW': 628163.090548054, 'HAL': 10684218.034948371, 'HAS': 1304916.510722796, 'HBAN': 10289948.698967434, 'HBI': 3969971.6179507547, 'HCA': 3229329.355837967, 'HCN': 2147373.3407466244, 'HCP': 3345202.648133439, 'HD': 5612783.840349483, 'HES': 3608127.664813344, 'HIG': 3265715.447180302, 'HII': 332637.9253375695, 'HLT': 2536415.1195652173, 'HOG': 2138452.534551231, 'HOLX': 2723707.2112787925, 'HON': 2993908.5361397937, 'HPE': 11664639.388984509, 'HPQ': 12578830.960413082, 'HP': 1773571.97299444, 'HRB': 2890863.5488482923, 'HRL': 2084104.1683876093, 'HRS': 802896.1564733916, 'HSIC': 1029358.3677521843, 'HST': 7621527.860206513, 'HSY': 1135862.1032565527, 'HUM': 1441347.2795869738, 'IBM': 4352535.480540112, 'ICE': 3584690.866028708, 'IDXX': 717869.6266878475, 'IFF': 443823.5035742653, 'ILMN': 1343873.8411437648, 'INCY': 1585684.7704527404, 'INFO': 1440383.5790621592, 'INTC': 29326713.900714852, 'INTU': 1701220.7084988086, 'IPG': 4491268.3749007145, 'IP': 3158104.383637808, 'IQV': 984176.4193817878, 'IRM': 1653384.456711676, 'IR': 2032714.8895949165, 'ISRG': 1140628.777601271, 'ITW': 1687350.7847498015, 'IT': 459504.09213661635, 'IVZ': 3335801.8117553615, 'JBHT': 888360.3193010326, 'JCI': 3723501.131056394, 'JEC': 1026252.5663224781, 'JNJ': 7606657.673550437, 'JNPR': 5791269.08101668, 'JPM': 16589033.246227164, 'JWN': 2284699.419380461, 'KEY': 11612727.7299444, 'KHC': 3314303.112977099, 'KIM': 3395779.837172359, 'KLAC': 1543040.1509134234, 'KMB': 1795463.4503574264, 'KMI': 13516693.4725973, 'KMX': 2012341.5647339157, 'KORS': 3461911.501985703, 'KO': 13742587.914217632, 'KR': 8859911.963463066, 'KSS': 3401699.226370135, 'KSU': 1246193.8363780777, 'K': 2053022.3471008737, 'LB': 2544964.198570294, 'LEG': 984472.0103256552, 'LEN': 3436372.225575854, 'LH': 884683.2382843527, 'LKQ': 1858049.7434471804, 'LLL': 649444.4876886418, 'LLY': 4694385.003971406, 'LMT': 1529610.9197776013, 'LNC': 2032643.4678316123, 'LNT': 1230025.783161239, 'LOW': 5928936.038125496, 'LRCX': 2211512.298649722, 'LUK': 1689384.5226370136, 'LUV': 6799713.157267673, 'LYB': 3486587.4861000795, 'L': 1064189.2692613185, 'MAA': 601451.2231930103, 'MAC': 1169475.760127085, 'MAR': 2652236.023034154, 'MAS': 3962446.7180301826, 'MAT': 4793055.395552025, 'MA': 4591886.181890389, 'MCD': 5150398.102462271, 'MCHP': 2218817.437648928, 'MCK': 1568788.3669579031, 'MCO': 1086449.8633836377, 'MDLZ': 8979732.710881652, 'MDT': 5662533.451945988, 'MET': 6467918.124702144, 'MGM': 8722944.131056394, 'MHK': 680868.760127085, 'MKC': 713485.1477362986, 'MLM': 715539.2605242255, 'MMC': 2079731.7744241462, 'MMM': 2302662.2795869736, 'MNST': 3786129.639396346, 'MON': 3024216.5369340745, 'MOS': 4366893.496425735, 'MO': 7211928.772041302, 'MPC': 5883098.996822875, 'MRK': 11312748.61477363, 'MRO': 11674367.720413025, 'MSFT': 33869462.74583002, 'MSI': 1538384.543288324, 'MS': 12057364.586973788, 'MTB': 827528.3383637808, 'MTD': 170365.17394757745, 'MU': 30248411.18903892, 'MYL': 5750885.85782367, 'M': 6331553.343129468, 'NAVI': 3198619.546875, 'NBL': 3791614.9888800634, 'NCLH': 1452601.49324861, 'NDAQ': 1121027.321683876, 'NEE': 2053307.3471008737, 'NEM': 7768097.128673551, 'NFLX': 16208007.963463066, 'NFX': 3099805.027799841, 'NI': 2490807.3288324066, 'NKE': 8398731.98570294, 'NLSN': 2541338.123907863, 'NOC': 1144918.900714853, 'NOV': 4322268.953931692, 'NRG': 5078764.903097697, 'NSC': 1879696.0460683082, 'NTAP': 3925298.257347101, 'NTRS': 1225122.2930897537, 'NUE': 2396489.4590945193, 'NVDA': 10465799.544082604, 'NWL': 3392146.6266878475, 'NWSA': 3438939.24037639, 'NWS': 1010693.0940975193, 'OKE': 2303382.5814138204, 'OMC': 1693418.271644162, 'ORCL': 16003635.342879873, 'ORLY': 840624.0190627482, 'OXY': 4562099.872915012, 'O': 1963930.7292506043, 'PAYX': 2167482.8514694204, 'PBCT': 3359075.0643367753, 'PCAR': 1938611.9467831613, 'PCG': 3107016.904686259, 'PCLN': 630292.6584590945, 'PDCO': 968354.6822875298, 'PEG': 3141147.8800635426, 'PEP': 4514717.656870532, 'PFE': 28218910.923749007, 'PFG': 1360958.0127084989, 'PGR': 3379297.1366163623, 'PG': 8966642.281175537, 'PHM': 6303634.393169182, 'PH': 1163719.5321683877, 'PKG': 950615.3613979348, 'PKI': 787695.7474185862, 'PLD': 2716866.35822081, 'PM': 4627417.274027006, 'PNC': 2390965.0063542495, 'PNR': 1280104.3939634631, 'PNW': 818361.108816521, 'PPG': 1601671.6449563145, 'PPL': 4442348.9213661635, 'PRGO': 1515242.9785544083, 'PRU': 2425830.7839555205, 'PSA': 733367.0246227165, 'PSX': 3249398.885623511, 'PVH': 1042719.8316123908, 'PWR': 2082162.6123907864, 'PXD': 1910634.746624305, 'PX': 1320430.0015885623, 'PYPL': 8854490.015267175, 'QCOM': 11098346.215250198, 'QRVO': 1816065.770806658, 'RCL': 2061783.1938046068, 'REGN': 879377.4300476947, 'REG': 700869.2144559174, 'RE': 344747.58935663226, 'RF': 16398451.548848292, 'RHI': 1069717.325655282, 'RHT': 1684832.7490071484, 'RJF': 789930.7378872121, 'RL': 1086690.9936457507, 'RMD': 964707.8983320096, 'ROK': 905779.8490865766, 'ROP': 460262.85941223195, 'ROST': 3072941.142970612, 'RRC': 3851102.456711676, 'RSG': 1475662.044479746, 'RTN': 1729189.2184273233, 'SBAC': 1182034.4011119937, 'SBUX': 9230516.611596506, 'SCG': 1017305.0444797458, 'SCHW': 8176124.504368546, 'SEE': 2019353.352660842, 'SHW': 712112.2144559174, 'SIG': 1237261.2088959492, 'SJM': 833941.0444797458, 'SLB': 7287461.7299444005, 'SLG': 742849.9237490072, 'SNA': 421194.4741858618, 'SNI': 1139731.809372518, 'SNPS': 802240.7498014297, 'SO': 5026764.164416203, 'SPGI': 1322271.3463065925, 'SPG': 1457440.6354249404, 'SRCL': 691720.9714058777, 'SRE': 1215602.3073868148, 'STI': 3696698.131056394, 'STT': 2421891.374900715, 'STX': 4489437.335980937, 'STZ': 1530969.8498808579, 'SWKS': 3194068.34471803, 'SWK': 1148015.53375695, 'SYF': 6005980.353603603, 'SYK': 1365451.3073868148, 'SYMC': 6900795.079428118, 'SYY': 3705860.960285941, 'TAP': 1617744.922954726, 'TDG': 512264.17950754566, 'TEL': 1767532.348689436, 'TGT': 5678874.949960286, 'TIF': 1490979.0063542493, 'TJX': 3656175.7942811754, 'TMK': 612051.5694996029, 'TMO': 1793787.0849880858, 'TPR': 4117990.474980143, 'TRIP': 2321225.9841143764, 'TROW': 1508215.0206513104, 'TRV': 1858723.4646544878, 'TSCO': 1409712.9714058777, 'TSN': 3781991.941223193, 'TSS': 1287097.9118347894, 'TWX': 5221944.732327244, 'TXN': 6018961.555996823, 'TXT': 1925221.8252581414, 'T': 25298330.478951547, 'UAA': 5652010.153296267, 'UAL': 5299701.248610008, 'UA': 3370192.887688985, 'UDR': 1651598.9563145353, 'UHS': 816243.5115170771, 'ULTA': 1013662.320889595, 'UNH': 4019056.461477363, 'UNM': 1611633.6671961874, 'UNP': 4263048.288324066, 'UPS': 3027247.5448768865, 'URI': 1892244.2589356632, 'USB': 7142589.941223193, 'UTX': 3802275.8610007945, 'VAR': 771545.1739475775, 'VFC': 2403062.632247816, 'VIAB': 3829077.0174741857, 'VLO': 6451987.977760127, 'VMC': 1049429.8316123907, 'VNO': 903132.6393963463, 'VRSK': 859428.298649722, 'VRSN': 1127986.9650516282, 'VRTX': 1860544.9554848967, 'VTR': 2116030.90548054, 'VZ': 16093070.656870533, 'V': 10075848.808578236, 'WAT': 500379.5798252581, 'WBA': 5432793.386020651, 'WDC': 3363797.9475774425, 'WEC': 1775572.5194598888, 'WFC': 18511480.962668784, 'WHR': 978465.3717235902, 'WLTW': 785482.178030303, 'WMB': 8013220.940428912, 'WMT': 8175689.6187450355, 'WM': 2014002.0397140589, 'WRK': 1703380.9228441755, 'WU': 5365383.988880063, 'WYNN': 2437519.782366958, 'WYN': 1147585.6449563145, 'WY': 4258756.950754567, 'XEC': 1124747.8649722002, 'XEL': 3068818.832406672, 'XLNX': 3057583.12867355, 'XL': 2228249.1795075457, 'XOM': 12399217.393169181, 'XRAY': 1203439.7545671167, 'XRX': 2376838.2637013504, 'XYL': 1183141.1366163623, 'YUM': 3209031.5917394757, 'ZBH': 1297143.6600476569, 'ZION': 2621177.9126290707, 'ZTS': 3681878.482922955}

Top 10 stocks with highest trade volume :  dict_keys(['BAC', 'AAPL', 'GE', 'F', 'FB', 'MSFT', 'AMD', 'MU', 'INTC', 'CSCO'])